### ISSUE TITLE
Release 0.15.3 tracking issue

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#1773]
For making the release, there are the following things left to do:

- [x] Fix upgrade document on release-0.15
- [ ] backport upgrade document changes to master as well
- [x] update image versions in release-0.15
- [x] 0.15.3 release notes
