### ISSUE TITLE
Remove IngressRoute support

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1789]
This is a tracking issue for the removal of IngressRoute support.

IngressRoute was deprecated with the release of Contour 1.0.0-beta.1. Our plan is to remove support for IngressRoute in Contour 1.1 or 1.2 once the following issues are resolved.

Blockers:

- [x] #899 Replacement for `prefixRewrite`
- [x] #1689 IngressRoute to HTTPProxy upgrade tool

Remaining:
- [x] Confirm we've got enough right for users to be able to migrate.
- [x] Get community agreement that the 1.6 timeframe is when this will happen.
- [x] Confirm the timeline around removing the CRD definitions from the repo (may trail code removal by a bit, in case they are being consumed elsewhere.)
- [x] Code removal issue and execution. #2572
- [x] CRD removal issue and execution. #2655

**Comment by youngnick** [comment]
Moved to "In Progress" as I'm starting to get this work scheduled and speced out.

**Comment by youngnick** [comment]
Now that #2572 is finished, we just need to wait a while, I'd say one release, to then remove the IngressRoute types from the repo as well.

**Comment by davecheney** [comment]
🎉

**Comment by skriss** [comment]
@stevesloka now that #2655 is merged, can this issue be closed out?

It does look like there are still a handful of misc. references to IngressRoute in docs, function names, etc. - I can work on removing the remaining ones.

**Comment by stevesloka** [comment]
@skriss yup we can remove.  I'm not sure what's left in the repo, I thought I did a good comb through after @youngnick did. Feel free to add another PR to clean that up. =)

**Comment by davecheney** [comment]
Excellent. Please continue to erase my mistakes.
