### ISSUE TITLE
Support Ingress V1 

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2139]
Kubernetes SIG Network is proposing a number of changes to the Ingress spec in order to graduate it to V1. Since Ingress is a standard common feature, we should evaluate whether Contour should support the V1 changes.

- [x] Ingress V1: path matching mode #2135
- [x] Ingress V1: support spec.backend field rename #2136
- [x] Ingress V1: support for service backends #2137
- [x] Ingress V1: hostname wildcard support #2138
- [x] Ingress V1: support IngressClass #2146
- [x] Detailed documentation on Contour Ingress v1 support: https://github.com/projectcontour/contour/issues/3469

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md

**Comment by youngnick** [comment]
This issue is no longer blocked, and needs a design document. As it's related to the service-apis design, I'll get started on a design document for it as well.

**Comment by youngnick** [comment]
Sorry, I was unclear here. This work will need its own design document, separate to the service-apis one, but it will be similar, in that an IngressClass describes a Contour deployment and its associated Envoys - Contour will ignore the `parameters` field of the IngressClass, and will only use the oldest IngressClass that has a matching `controller` field. See the WIP PR #3213 in the GatewayClass section for inspiration.

**Comment by sunjayBhatia** [comment]
Not sure if the last step needs to be done as part of this or if we can call it pretty much done, all the ingress conformance tests are passing but flaky in CI/locally

**Comment by skriss** [comment]
Personally I'd call this one done and just leave the conformance issue open separately.

**Comment by sunjayBhatia** [comment]
Removed the ingress conformance tests item, closing this
