### ISSUE TITLE
Add support for rotation of xDS/gRPC certificates and keys

### ISSUE THREAD

**Issue by tsaarni** [projectcontour/contour#2143]
Problem statement: Contour does not provide support for certificate rotation for the control plane (xDS/gRPC) connection between Contour and Envoy.

It shall be possible to replace the certificates and keys and have them taken into use automatically. Rotation shall not cause interruptions for data plane traffic.

Tasks:

- [X] #2198 Add support for Contour to hot-reload certificates and key
- [x] #2333 Generate reloadable bootstrap configuration for Envoy
- [x] #2524 Flip default deployment over to use reloadable bootstrapping
- [x] #2229 Update deployment documentation for certificate rotation
- [x] #2538 certgen doesn’t have enough RBAC permissions to update secrets
- [x] #2537 Stop using ImagePullPolicy of Always
- [x] #2494 Certgen should generate secrets that are compatible with cert-manager

**Comment by tsaarni** [comment]
This topic was discussed at [community meeting](https://hackmd.io/84Xbl4WBTpm7OBhaOAsSiw) on Jan 21th.  As agreed, renewal of certificates and keys is scoped out.

I would like to work with this issue.

Would it be OK to create two PRs:

1. Add support for Contour to hot-reload certificates and key
2. Generate bootstrap configuration according to outcome of https://github.com/envoyproxy/envoy/issues/9359

Is the scope already well understood or should separate design document be created?

**Comment by davecheney** [comment]
SGTM. Thank you.

**Comment by jpeach** [comment]
Tasks:

- [X] #2198 Add support for Contour to hot-reload certificates and key #2198
- [ ] #2333 Generate reloadable bootstrap configuration for Envoy
- [ ] Flip default deployment over to use reloadable bootstrapping
- [ ] Update deployment documentation for certificate rotation

**Comment by jpeach** [comment]
Assigning myself since I'm shepherding @tsaarni's work on this project.

**Comment by jpeach** [comment]
All the task here are complete.
