### ISSUE TITLE
Set load balancer address on HTTPProxy objects

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2371]
**Please describe the problem you have**

The Ingress status exposes the load balancer IP address so that ingresses can automatically be registered in DNS, or directly accessed. We should add the same capabilities to HTTPProxy.

Updated todo from @youngnick:

- [x] Add a StatusUpdateHandler that takes status updates for Ingress objects from `k8s.StatusAddressUpdater` (renamed from IngressStatusUpdater), and applies them to the apiserver if they're an actual change. This is done with an interface (`k8s.StatusUpdater`) with a caching implementation for testing, and a writing implementation for actual use. This is PR #2530. 
- [x] Add support for HTTPProxy to `k8s.StatusAddressUpdater`. This will produce some raciness similar to #2522, which should be mitigated by the next step. This is PR #2551 
- [x] ~~Move the existing DAG rebuild status updates to use StatusUpdateHandler, including adding support for IngressRoute and HTTPProxy `valid` and `desc` fields. This may involve a small update to IngressRoute to enable the `status` subresource, so that the same code paths can be used for everything.~~ Moved this work to #2560.

**Comment by jpeach** [comment]
xref #403

**Comment by jpeach** [comment]
Moving to the current work stream to match the status of #403

**Comment by stevesloka** [comment]
We need to come up with at least a high-level design doc on this first before implementing anything different in Status I would recommend.

**Comment by youngnick** [comment]
I think that the loadBalancer stanza is standard enough we could just add it to HTTPProxy wholesale, and leave the other conditions work until later.

This would give HTTPProxy the same functionality as Ingress for a minimal investment.

**Comment by youngnick** [comment]
After discussing today, I'm going to go ahead with just bringing the `loadBalancer` stanza from Ingress and Service into `status` on HTTPProxy, and updating it in the same way as we do for Ingress today.

**Comment by youngnick** [comment]
So, turns out that doing the HTTPProxy status the same way as we do for Ingress doesn't work, as there are then two places updating the status, and neither of them will retry if the other has updated a status while they were working.

We *could* address this with `RetryOnConflict` from client-go, but I think there's an opportunity here to refactor to make the further changes coming from #2495 easier to implement.

I'm going to do a small PoC on having Contour have a single status-updating goroutine that takes status updates via a channel with a struct containing the details of a Kube object, and a mutation function that will mutate the status of that object. The contract is then that the status-updating goroutine retrieves the most recent version of the referenced object, mutates the object with the function, then sends the mutated object back to the apiserver.

Theoretically, this means that we can send status updates from anywhere in Contour via this channel, meaning that as we add Conditions, we can update them from anywhere.

Let's see how it goes.

**Comment by youngnick** [comment]
After a small PoC, I have a plan, to be implemented in a series of PRs.

- [ ] Add a StatusUpdateHandler that takes status updates for Ingress objects from `k8s.StatusAddressUpdater` (renamed from IngressStatusUpdater), and applies them to the apiserver if they're an actual change. This is done with an interface (`k8s.StatusUpdater`) with a caching implementation for testing, and a writing implementation for actual use.
- [ ] Add support for HTTPProxy to `k8s.StatusAddressUpdater`. This will produce some raciness similar to #2522, which should be mitigated by the next step.
- [ ] Move the existing DAG rebuild status updates to use StatusUpdateHandler, including adding support for IngressRoute and HTTPProxy `valid` and `desc` fields. This may involve a small update to IngressRoute to enable the `status` subresource, so that the same code paths can be used for everything.

This will have the effect of serializing status update writes to the apiserver, always ensuring that the latest version of the object is modified, with all the benefits and costs that entails.

Benefits:
- Ensures no "This object has been modified" errors can occur for status updates.
- Abstracting the actual writes behind an interface for StatusAddressUpdater ensures it can be tested in unit tests.
- Prepares the code for adding more complexity to status updates (that is, #2495)

Costs and risks:
- By creating a single place where updates are performed, we risk some performance hit. I hope that this will be minimal because we're only applying status updates that have a diff - read operations from the apiserver are pretty cheap. We will need to keep an eye out for performance here though.
- Having a single place that updates status means there's a single place those updates can fail; this should be mitigated with testing.

**Comment by youngnick** [comment]
Moved remaining work to #2560 as it's more than I initially thought.
