### ISSUE TITLE
Rename references of service-apis to gateway-api

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3349]
Following up to https://github.com/kubernetes-sigs/service-apis/issues/536, we need to rename Contour references of `service-apis` to `gateway-api`.

- [x] Rename GH labels (#3350)
- [x] Rename imports (#3370)
- [x] Update code comments (#3370)
- [x] Update design doc (#3397)

**Comment by skriss** [comment]
Assigning to @youngnick to finish up with the design doc per https://github.com/projectcontour/contour/pull/3370#issuecomment-782970543

**Comment by youngnick** [comment]
Closing this one out.
