### ISSUE TITLE
test/e2e: Upgrade testing epic

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour#3679]
This issue is a top-level/epic for capturing todos and progress on establishing an upgrade test suite for contour (roughly in order)

- [x] Build contour image once in CI, share between various e2e jobs
  - Should speed up e2e jobs and ensure we are actually testing against the same artifact
- [x] Initial upgrade test suite: #3678
- [x] Fix upgrade tests for all branches: #3743
- [ ] Upgrade tests should ensure uptime of an app during upgrade
  - Currently just tests routability before/after upgrade
  - [x] Will require multiple nodes in kind/cluster/replicas of app: https://github.com/projectcontour/contour/pull/4176
  - Will require defining some SLO that we need to fulfill during an upgrade (X% of requests succeed with 200 etc.)
- [ ] Upgrade tests should ensure creation of routes during upgrade works
  - Will require defining some SLO that we need to fulfill during an upgrade (creating an Ingress/HTTPProxy etc. works and route is enabled within X time etc.)
- [ ] Upgrade tests should deploy "upgrade from" version rather than relying on cluster running it already to support multiple upgrade scenarios
  - To reduce test time, we should lower the shutdown-manager drain/wait timeouts so that the Envoy pods can be deleted/recreated more quickly
