### ISSUE TITLE
Docs: Cleanup after Hugo migration

### ISSUE THREAD

**Issue by jonasrosland** [projectcontour/contour#3712]
There are a few instances within the docs which still have artifacts left over from the Jekyll to Hugo migration. These instances have all been fixed in v1.15.1 and main, but still remain in previous versions.

This will be a tracking issue for the fixes, so if you want to just fix part of the list please do so and reference this issue.

The list below shows how the artifacts impact the v1.15.0 docs, and if you fix them please also fix the previous versions impacted so we can mark them as complete.

- [x] https://projectcontour.io/docs/v1.15.0/architecture/ has a .center-image tag (twice) (#3755)
- [x] https://projectcontour.io/docs/v1.15.0/config/fundamentals has tag {% highlight yaml linenos %} | {% endhighlight %} as well as md link at the bottom: [4]: {% link docs/{{page.version}}/config/api.md %} (#3756)
- [x] https://projectcontour.io/docs/v1.15.0/config/virtual-hosts/ has link examples directory which 404s (#3758, #3757)
- [x] https://projectcontour.io/docs/v1.15.0/config/inclusion-delegation/ has link conditions which 404s (#3765)
- [x] https://projectcontour.io/docs/v1.15.0/config/tls-termination/ link to Contour configuration file 404s
- [x] https://projectcontour.io/docs/v1.15.0/config/upstream-tls/ has markdown links at the bottom (#3767)
- [x] https://projectcontour.io/docs/v1.15.0/config/request-routing/ under Header Conditions section, missing bullet arrow for notpresent, and on the same page: retryPolicy.count & retryPolicy.perTryTimeout has extra indentation
- [x] https://projectcontour.io/docs/v1.15.0/config/client-authorization/ under section Scoping Authorization Policy Settings link to authorization policy 404s, and same page: extra md link at bottom (#3768)
- [x] https://projectcontour.io/docs/v1.15.0/config/annotations/ under first section has missing link [HTTPProxy API][15], and markdown links at the bottom (#3777)
- [x] https://projectcontour.io/docs/v1.15.0/deploy-options/ example manifest link 404s, and a bunch of broken links and markdown links at the bottom (#3778)
- [x] https://projectcontour.io/docs/v1.15.0/configuration/#configuration-file tables has {: class="table thead-dark table-bordered"} inline, and an extraneous `<br>`, and on the same page link to `example manifests` 404s (#3780)
- [x] https://projectcontour.io/docs/v1.15.0/grpc-tls-howto/ certgen.yaml link 404s, and links to _integration/cert-envoy.ext. 404
- [x] https://projectcontour.io/docs/v1.15.0/config/tls-termination/ link to Contour configuration file 404s, should be https://github.com/projectcontour/contour/blob/main/examples/contour/01-contour-config.yaml (#3766)
- [x] Edit button on the docs right-hand side go to dead links, needs to be updated in https://github.com/projectcontour/contour/blob/main/site/themes/contour/layouts/partials/docs-right-bar.html (#3754)
- [ ] Various references to images use the `{% link ... %}` syntax and need to be updated (see https://github.com/projectcontour/contour/issues/3804 and https://github.com/projectcontour/contour/pull/3809 for reference)

Fixes for the above in v1.15.1 and main can be found in the following commits:
https://github.com/projectcontour/contour/pull/3704/commits/12b7cec133b9008b42176193081cd4e32b331c48
https://github.com/projectcontour/contour/pull/3704/commits/fe829834975a0fe2288350a3dff043d0754eed5d

**Comment by johanbrandhorst** [comment]
https://projectcontour.io/docs/v1.15.0/config/api/ is showing an empty page altogether.

**Comment by johanbrandhorst** [comment]
Edit buttons on some (all?) pages are dead links.

**Comment by jonasrosland** [comment]
> https://projectcontour.io/docs/v1.15.0/config/api/ is showing an empty page altogether.

Yup, that's covered in this issue: https://github.com/projectcontour/contour/issues/3708

**Comment by jonasrosland** [comment]
> Edit buttons on some (all?) pages are dead links.

Perfect, added to the list!

**Comment by a-mccarthy** [comment]
@jonasrosland the last un-checked item on this list is 
> https://projectcontour.io/docs/v1.15.0/grpc-tls-howto/ certgen.yaml link 404s, and links to _integration/cert-envoy.ext. 404
which appears to have been resolved in https://github.com/projectcontour/contour/pull/3785.

Is there any other clean up needed for this issue? or should we close it?

**Comment by sunjayBhatia** [comment]
yeah, I can check that one off

I think there are various references to images that are still wrong, similar to https://github.com/projectcontour/contour/issues/3804

**Comment by mzrithm** [comment]
I will work on repairing broken links to images as I discover them and will reference this issue.

**Comment by skriss** [comment]
Closing this out, if there are any issues with current docs they can be addressed individually.
